# Automatically switch to Chromecast when it begins playing
- id: switch_to_chromecast
  alias: Switch to Chromecast
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'playing'
  action:
    - service: script.power_on
    - service: script.input_bd
# Automatically switch to Kodi when it begins playing
- id: switch_to_Kodi
  alias: Switch to Kodi
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.living_room_kodi
    to: 'playing'
  action:
    - service: script.power_on
    - service: script.input_dvd
# Adjust Stereo Volume with Slider
- id: adjust_stereo_volume
  alias: Set Stereo Volume
  trigger:
    platform: state
    entity_id: input_slider.stereo_volume_slider
  action:
    - service: shell_command.set_volume_level
      data_template:
        target_volume: '{{states.input_slider.stereo_volume_slider.state | int}}'
        host: !secret stereo_ip
        port: !secret stereo_port
# Turn off the light when watching a Movie
- id: lights_out_movie
  alias: Turn Off the Light when a Movie Starts Playing
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.living_room_kodi
      to: 'playing'
    - platform: state
      entity_id: media_player.tv
      to: 'playing'
  condition:
    condition: time
    after: '18:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_light
# Turn On the lights when the movie is over or stopped
- id: lights_on_movie
  alias: Turn On the Light after a Movie
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.living_room_kodi
      from: 'playing'
    - platform: state
      entity_id: media_player.tv
      from: 'playing'
  condition:
    condition: time
    after: '18:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_light
