# xBox Live API
- platform: xbox_live
  api_key: !secret xbox_api_key
  xuid: !secret xbox_uid
# Yahoo Weather
- platform: yweather
  weoid: !secret where_on_earth
  monitored_conditions:
    - weather
    - weather_current
    # - temp_min
    # - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature
# Octoprint
- platform: octoprint
  name: OctoPrint
  monitored_conditions:
    - Current State
    - Job Percentage
    - Temperatures
    - 'Time Remaining'
    - 'Time Elapsed'

- platform: template
  sensors:
    hotend:
     friendly_name: 'Hotend Actual'
     value_template: "{{ ((states.sensor.octoprint_actual_tool0_temp.state | float-32) | float*(5/9)) | round(2) }} 째C"
    bed:
     friendly_name: 'Bed Actual'
     value_template: "{{ ((states.sensor.octoprint_actual_bed_temp.state | float-32) | float*(5/9)) | round(2) }} 째C"
    hotend_target:
     friendly_name: 'Hotend Target'
     value_template: "{{ ((states.sensor.octoprint_target_tool0_temp.state | float-32) | float*(5/9)) | round(2) }} 째C"
    bed_target:
     friendly_name: 'Bed Target'
     value_template: "{{ ((states.sensor.octoprint_target_bed_temp.state | float-32) | float*(5/9)) | round(2) }} 째C"
    time_remainng:
      friendly_name: 'Time Remaining'
      unit_of_measurement: 'hours'
      value_template: "{{ (states.sensor.octoprint_time_remaining.state |float / 3600) | round(2) }}"
    time_elapsed:
      friendly_name: 'Time Elapsed'
      unit_of_measurement: 'hours'
      value_template: "{{ (states.sensor.octoprint_time_elapsed.state |float / 3600) | round(2) }}"
