# xBox Live API
- platform: xbox_live
  api_key: !secret xbox_api_key
  xuid: !secret xbox_uid
# Yahoo Weather
- platform: yweather
  weoid: !secret where_on_earth
  monitored_conditions:
    - weather
    - weather_current
    # - temp_min
    # - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature
