# MQTT switch control
- platform: mqtt
  name: "Living Room Light"
  command_topic: "cmnd/sonoff_switch_1/POWER"
  state_topic: "stat/sonoff_switch_1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
#
- platform: mqtt
  name: "Bed Room Light"
  command_topic: "cmnd/sonoff_switch_2/POWER"
  state_topic: "stat/sonoff_switch_2/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
